---
- name: Configure nginx webserver
  hosts: aws
  tasks:
  - name: install httpd server
    become: yes
    become_user: root
    yum:
      name: httpd
      state: latest
  - name: start httpd server
    shell:
      "sudo systemctl start httpd"
      
      
